apiVersion: v1
kind: ServiceAccount
metadata:
  name: db-secrets-reader
  namespace: "{{namespace}}"
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::121897425968:role/ibank-eks-dev-db-secrets-reader
