apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: ibank-postgres
spec:
  provider: aws
  parameters:
    objects: |
      - objectName: {{ .Values.secretsStore.secretId | quote }}
        objectType: "secretsmanager"
        jmesPath:
          - path: "username"
            objectAlias: "spring.datasource.username"
          - path: "password"
            objectAlias: "spring.datasource.password"
